### ISSUE TITLE
[BUG] Impossible to send new reference

### ISSUE THREAD

**Issue by Lauraillouz** [Refemi/refemi_front#110]
Impossible to send new reference, it goes back to the title field.

**Comment by Lauraillouz** [comment]
@gaeVG could you have a look at this?

**Comment by gaeVG** [comment]
@Laura the problem has been partially solved: I was able to fix the blocking of the upload but I can't integrate the confirmation of the other inputs. Indeed, the elements to validate the country, or the themes (and incidentally the date, I don't know why) don't work correctly, which corrupts the form a bit since what is not filled in should prevent the confirmation and the sending to the server.
This is indeed not a problem for the current ticket, but what should we do about this problem? I think that the modules we use, especially for input lists, cannot be compatible with the react-form module we use to send the form. Should we change the input modules or change the way we send the form?
