### ISSUE TITLE
[BUG] Theme selection does not work with Firefox

### ISSUE THREAD

**Issue by gaeVG** [Refemi/refemi_front#111]
In the add reference form, it is not possible to interact with the themes field.

![firefox_vX5oKzedwz](https://user-images.githubusercontent.com/16835349/166250502-6d2a4273-85e3-4199-a642-8964cc019f21.png)

After different tests on different browsers, I have the impression that the bug does not occur with a Chromium ported browser. I noticed the problem with Firefox, but I didn't have the opportunity to test on Safari.

**Comment by Lauraillouz** [comment]
For now I cannot log in anymore when I'm on Firefox. I think it's due to your updates on the CORS parameters. Let's talk about it and see what we can do!

**Comment by Lauraillouz** [comment]
@gaeVG I have done some research and must say I am a bit confused on the reason why this is not working.
So I have asked directly the library contributors for help: https://github.com/JedWatson/react-select/discussions/5294
Let's wait and see waht they say. Hopefully it's not a silly mistake and I don't ridicule myself, haha

**Comment by Lauraillouz** [comment]
Ok so the probleme was that for some reason on Frefox, the Select component was going inside the fieldset above. It wasn't clickable anymore.
The solution (maybe temporary) I found was to add some style specifically for firefox so that the theme selection is clickable again. It's not too annoying in terms of overall style.
