### ISSUE TITLE
Links to categories do not work in the widget

### ISSUE THREAD

**Issue by gaeVG** [Refemi/refemi_front#56]
Seen during the presentation, the links do not refer to the categories on which one clicks

**Comment by gaeVG** [comment]
I tried to remove the windowsScroll when usingEffect of References and ListReferences, but I still can't understand why the link doesn't reach the anchor placed on the titles (I also tried to place them on the section tags, without success).
@Lauraillouz if you have an idea 🤞

**Comment by Lauraillouz** [comment]
Yeah I know what to do I think. I'll have a look

**Comment by Lauraillouz** [comment]
So from what I could see, I think the issue came from using a <a></a> link and href (first mistake).
However, using <Link /> and "to" attribute isn't the solution, cause it's apparently a common issue for it to not working with anchors.
I had to install [react-router-hash-link](https://www.npmjs.com/package/react-router-hash-link) and now it's all good.

Note that the widget covers the reached title. I am not fixing it because we're planning on removing the widget et make it a sidebar menu. We'll see what we decide about that in another ticket.

See branch 56-fix-widget-categories-anchors
