### ISSUE TITLE
[Design] Verify sass

### ISSUE THREAD

**Issue by Lauraillouz** [Refemi/refemi_front#95]
We need to look over every sass file and make sure that we have nested classes and not nested html tags.
Nesting html tags can cause issues in the future, when we use them differently in the same class. 
Using classes helps to target elements for their role instead of their semantic.

**Comment by gaeVG** [comment]
@Laura I did not pay attention on this point but it has a shift of the buttons following your merge:

![image](https://user-images.githubusercontent.com/16835349/164006926-d608a560-6d7a-47df-9c2a-2582e51ece93.png)

The test server has not been updated yet and it is clear that the bug is not present.
